[package]
name = "meta"
version = "0.1.0"

[dependencies]
error-chain = "0.11"
lazy_static = "0.2.1"
rand = "0.3"
regex = "0.1"
reqwest = "0.8"
serde = "1"
serde_derive = "1"
serde_json = "1"
toml = "0.1"
url = "1.1.1"
walkdir = "0.1"

find-unimplemented-tasks = { path = "../tasks/rosetta-code/find-unimplemented-tasks" }
